# Generated by Django 2.0.6 on 2018-07-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minu',
            name='month',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='minu',
            name='year',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
