# Generated by Django 2.0.6 on 2018-07-08 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='DHU',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quality',
            name='FTR',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quality',
            name='line_no',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='total_checked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quality',
            name='total_defects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quality',
            name='total_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quality',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 8, 10, 57, 52, 658427)),
        ),
    ]
