# Generated by Django 2.0.6 on 2018-07-11 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0002_auto_20180708_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_checked', models.IntegerField(default=0)),
                ('total_defects', models.IntegerField(default=0)),
                ('total_passed', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='quality',
            old_name='line_no',
            new_name='EP_1',
        ),
        migrations.RemoveField(
            model_name='quality',
            name='total_checked',
        ),
        migrations.RemoveField(
            model_name='quality',
            name='total_defects',
        ),
        migrations.RemoveField(
            model_name='quality',
            name='total_passed',
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_10',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_11',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_12',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_13',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_14',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_15',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_16',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_17',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_18',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_19',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_2',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_20',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_21',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_22',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_23',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_24',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_3',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_4',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_5',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_6',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_7',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_8',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='quality',
            name='EP_9',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
