# Generated by Django 2.0.6 on 2018-07-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0003_auto_20180711_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quality',
            name='DHU',
        ),
        migrations.RemoveField(
            model_name='quality',
            name='FTR',
        ),
    ]
