# Generated by Django 2.0.6 on 2018-07-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0004_auto_20180711_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='EP_1',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_10',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_11',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_12',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_13',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_14',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_15',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_16',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_17',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_18',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_19',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_2',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_20',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_21',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_22',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_23',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_24',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_3',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_4',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_5',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_6',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_7',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_8',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='quality',
            name='EP_9',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
