# Generated by Django 2.0.6 on 2018-07-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0005_auto_20180711_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='category',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='quality',
            name='department',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='quality',
            name='factory_name',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='quality',
            name='item_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quality',
            name='section',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='quality',
            name='style_name',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='quality',
            name='style_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quality',
            name='sub_category',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='quality',
            name='user_id',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='quality',
            name='user_name',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
