# Generated by Django 2.0.6 on 2018-07-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0006_auto_20180718_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quality',
            old_name='factory_name',
            new_name='factoryname',
        ),
    ]
