# Generated by Django 2.0.6 on 2018-07-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0007_auto_20180720_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quality',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='quality',
            name='user_name',
        ),
        migrations.AddField(
            model_name='quality',
            name='name',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
