# Generated by Django 2.0.6 on 2018-09-07 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=200)),
                ('phone', models.CharField(default=0, max_length=20)),
                ('address', models.TextField(default=0)),
                ('payment_option', models.CharField(default=0, max_length=50)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default=0, max_length=200)),
                ('product_details', models.TextField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('active', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sele', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='datas.product'),
        ),
    ]
