# Generated by Django 2.0.6 on 2018-07-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0003_auto_20180729_0635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ie',
            old_name='line',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='ie',
            old_name='efficiency',
            new_name='machine_oper',
        ),
        migrations.RenameField(
            model_name='ie',
            old_name='day',
            new_name='machines_line',
        ),
        migrations.RenameField(
            model_name='ie',
            old_name='operation_man',
            new_name='man_actual',
        ),
        migrations.RenameField(
            model_name='ie',
            old_name='style_name',
            new_name='man_budgeted',
        ),
        migrations.RenameField(
            model_name='ie',
            old_name='minutes_avaliable',
            new_name='mmr_actual',
        ),
        migrations.RenameField(
            model_name='ie',
            old_name='minutes_earned',
            new_name='mmr_budgeted',
        ),
        migrations.RenameField(
            model_name='ie',
            old_name='operation_hours',
            new_name='no_lines',
        ),
        migrations.RemoveField(
            model_name='ie',
            name='shift_hours',
        ),
        migrations.RemoveField(
            model_name='ie',
            name='shift_man',
        ),
    ]
